### ISSUE TITLE
How to use this with v2.7.3?

### ISSUE THREAD

**Issue by ChriFo** [woodpecker-ci/example-extensions#23]
I try to get this example to work with Woodpecker 2.7.3.

The documentation says:

> Finally go to your repository settings, to the extensions tab and set the URL of this server as the URL for the extension you want to test.

How to achieve this?

Thanks for your help in advance.

**Comment by ChriFo** [comment]
Alright.
Thanks for the hint to PR!

**Comment by s00500** [comment]
I assume the global config still works, where you have to pass the extensionendpoint to the server as environment, see here:

https://woodpecker-ci.org/docs/administration/server-config#woodpecker_config_service_endpoint

**Comment by s00500** [comment]
Hm... the repo ID will not be included in the request...
